### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}


###################################################################################################







###################################################################################################


### API Index Action
GET http://localhost:3000/api.json

### API Update Action
PATCH http://localhost:3000/api/1.json
Content-Type: application/json

{
  "forks": 20
}

