@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjQ4ODg1NTh9.bXmRlIDa30_5e1AcVZvtb_qy-EH3OXaow7R62sQWgBM

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "First Last",
  "email": "admin@test.com",
  "password": "password",
  "password_confirmation": "password"
}

###################################################################################################

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "password"
}

###################################################################################################






###################################################################################################


### API Index Action
GET http://localhost:3000/api.json

### API Update Action
PATCH http://localhost:3000/api/1.json
Content-Type: application/json

{
  "forks": 20
}

### React Getter
GET http://localhost:3000/react.json
Authorization: Bearer 


### Root Github API
GET http://localhost:3000/github.json


